// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace HappyTravel.Wakayama.Data.CompiledModels
{
    [DbContext(typeof(WakayamaContext))]
    public partial class WakayamaContextModel : RuntimeModel
    {
        static WakayamaContextModel()
        {
            var model = new WakayamaContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static WakayamaContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
